### PR TITLE
Fixed beacon timeout handling.

### LINKED ISSUE #2: Beacon timeout handling error
Hi,

the beacon timeout handling doesn't work in all cases.

Example: Beacon Timeout = 10, Beacon is sent at minute 52

Next Beacon is calculated (52 + 10) % 60 = 2

Next loop run in minute 53. Beacon will be sent because 2 < 53. Even worste beacon will be flooded.

Basically that happens in all cases when the next beacon is calculated for the next hour.

I will commit a fix for this.

### PR DESCRIPTION
**Pull request by raufaser**
I am using the time library and convert the gps time to unix timestamp. Now it is possible to use beacon timeout of any number of minutes. E.g. 300 = 5 hours.

closes #2

### CODE REVIEW

**Comment by peterus** [comment]
thanks for the pull request, i never got it perfectly running. I did some updates on mainline as there was a lot of maintenance missing in the last time.
Can you update your pull request with the last changes? - otherwise I can also add your changes, but than your name will not appear here which would be a pity

**Comment by raufaser** [comment]
tbh I have no idea how to do that. In theory it is absolutely clear to me what to do. I have to merge your new commits with my commit.  I guess I have to learn a lot about git and how to use it in Visual Studio Code. A lot of the teminology is still unclear to me. But I am willing to learn :)

**Comment by peterus** [comment]
if you have access to a console try this commands:

```
git remote add upstream https://github.com/lora-aprs/LoRa_APRS_Tracker.git
git fetch upstream
git rebase upstream/master
```

there is a high possibility that you will get merge conflicts, you can solve them very easy with visual studio code.
make a new commit and push it.

there is a high possibility that you have to force the push:

`git push -f origin master`

**Comment by raufaser** [comment]
Well. I gave my very best :) Thanks for the explanation.

**Pull request merged**
